server:
  compression:
    enabled: true
  servlet:
    context-path: /api
    session:
      tracking-modes:

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  info:
    build:
      enabled: false
    git:
      enabled: false
    java:
      enabled: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/manazr?allowMultiQueries=true
    username: app_user
    password: ${DB_PASS}
    hikari.maximum-pool-size: 3
    type: com.zaxxer.hikari.HikariDataSource

manazr:
  app:
    name: Manazr
    info:
      version: 1.0.0
  contributors:
    dev:
      - Swetank Subham
    qa:
      - Swetank Subham
