management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  info:
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true

manazr:
  app:
    info:
      stage: local
